### ISSUE TITLE
Composer/Packagist

### ISSUE THREAD

**Issue by Shmakov** [nkostadinov/EExcelView#9]
Thanks for working on this extension. I still use it on one of my legacy application and it works great.

Do you have any plans on having the extension available on the Packagist, so that it can be installed using composer?

Thank you for your help!

**Comment by nkostadinov** [comment]
I did a quick setup. You can try it at https://packagist.org/packages/nkostadinov/yii-eexcelview (not tested)

**Comment by Shmakov** [comment]
Thanks for quick response.

Just tried to install it using composer, however it didn't work. Here is the error message:

```
Your requirements could not be resolved to an installable set of packages.                                           
                                                                                                                     
  Problem 1                                                                                                          
    - Installation request for nkostadinov/yii-eexcelview * -> satisfiable by nkostadinov/yii-eexcelview[dev-master].
    - nkostadinov/yii-eexcelview dev-master requires yiisoft/yii 1.1 -> no matching package found.                   
                                                                                                                     
Potential causes:                                                                                                    
 - A typo in the package name                                                                                        
 - The package is not available in a stable-enough version according to your minimum-stability setting               
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.                                
 - It's a private package and you forgot to add a custom repository to find it                                       
                                                                                                                     
Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.                          
```

I could be wrong, but it might be because of the requires section. Possibly it should state: `yiisoft/yii: ~1.1.14` (or so)

And I'm afraid the same will happen with `php`, as currently it requires exact version (i.e. 5.3 and nothing else)

What do you think? Thank you!

**Comment by nkostadinov** [comment]
Yeah you are right. I made it quickly via console so I didn't take a look at the versions. I've modified them to : 

```
        "yiisoft/yii": "~1.1",
        "php": ">=5.3",
        "phpoffice/phpspreadsheet": "~1.10.1"
```

Can you see if it is OK ?

**Comment by Shmakov** [comment]
Thank you Nikola!

Do you know by any chance if EExcelView would work with `phpspreadsheet` of earlier version? Possibly `~1.8.2`? The current version that is specified in the composer (`~1.10.1`) requires `php: ^7.1`.

My project is using php 5.6 and I couldn't install the package, here is the log:

```
  Problem 1                                                                                                                              
    - phpoffice/phpspreadsheet 1.10.1 requires php ^7.1 -> your PHP version (5.6.40) does not satisfy that requirement.                  
    - nkostadinov/yii-eexcelview dev-master requires phpoffice/phpspreadsheet ~1.10.1 -> satisfiable by phpoffice/phpspreadsheet[1.10.1].
    - Installation request for nkostadinov/yii-eexcelview * -> satisfiable by nkostadinov/yii-eexcelview[dev-master].                    
```

**Comment by nkostadinov** [comment]
I dont know and i dont have an active yii 1 project currently to test it. I lowered the version though, there wasn't php 7 when I wrote this extension :). Hope it works now.

**Comment by Shmakov** [comment]
Thank you Nikola, I was able to install it now.
